NetRestaurant.UI/Areas/Admin/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using NetRestaurant.Infrastructure.Repositories;
using NetRestaurant.UI.ViewModels;
using System.Security.Claims;

namespace NetRestaurant.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("/admin/[controller]/[action]")]
    public class LoginController : Controller
    {
        private readonly UserRepository _userRepository;

        public LoginController(UserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public IActionResult Index()
        {
            return View(new LoginVM());
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginVM login)
        {
            var user = await _userRepository.GetByEmailPassword(login.Email, login.Password);
            if (user == null || !user.IsAdmin)
            {
                TempData["Error"] = "User does not exists or is not allowed";
                return View(login);
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Name),
                new Claim(ClaimTypes.Role, "Admin")
            };

            var identiy = new ClaimsIdentity(claims, "AdminCookie");
            var principal = new ClaimsPrincipal(identiy);

            await HttpContext.SignInAsync("AdminCookie", principal);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

NetRestaurant.UI/Controllers/LoginController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using NetRestaurant.Core.Entities;
using NetRestaurant.Infrastructure.Repositories;
using NetRestaurant.UI.ViewModels;
using System.Security.Claims;

namespace NetRestaurant.UI.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly IMapper _mapper;

        public LoginController(UserRepository userRepository, IMapper mapper)
        {
            _userRepository = userRepository;
            _mapper = mapper;
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginVM login)
        {
            try
            {
                var user = await _userRepository.GetByEmailPassword(login.Email, login.Password);

                if (user == null)
                {
                    return Json(new { success = false, message = "Invalid login credentials." } );
                }

                await Authenticate(user);

                return Json(new { success = true, redirectUrl = Url.Action("Index", "Dishes") });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "An unexpected error occurred. Please try again." });
            }
        }



        [HttpPost]
        public async Task<IActionResult> Register(UserVM userVM)
        {
            var user = _mapper.Map<UserVM, User>(userVM);

            try
            {
                if (user.Id == 0)
                    await _userRepository.Create(user);
                else
                    await _userRepository.Update(user);

                await Authenticate(user);

                TempData["Success"] = "The operation occurred successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "The operation has failed";
                return View(userVM);
            }

            return RedirectToAction("Index", "Dishes");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Dishes");
        }

        private async Task Authenticate(User user)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Name),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Role, "User")
            };

            var identiy = new ClaimsIdentity(claims, "UserCookie");
            var principal = new ClaimsPrincipal(identiy);

            await HttpContext.SignInAsync("UserCookie", principal);
        }
    }
}

NetRestaurant.UI/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetRestaurant.Core.Entities;
using NetRestaurant.Infrastructure.Repositories;
using System.Security.Claims;

namespace NetRestaurant.UI.Controllers
{
    [Authorize(AuthenticationSchemes = "UserCookie")]
    public class OrderController : Controller
    {
        private readonly OrderRepository _orderRepository;
        private readonly UserRepository _userRepository;

        public OrderController(OrderRepository orderRepository, UserRepository userRepository)
        {
            _orderRepository = orderRepository;
            _userRepository = userRepository;
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(Int64 dishId)
        {
            try
            {
                var userId = Convert.ToInt64(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var user = await _userRepository.Get(userId);

                var isDishAdded =  await _orderRepository.AddDishToOrder(user, dishId);

                var itemCount = await _orderRepository.GetOrderItemCount(user);

                if(isDishAdded)
                    return Json(new { success = true, itemCount });
                else
                    return Json(new { success = false, message = "You've already had this dish in your Order, Finish it or add new ones" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false });
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetOrderCount()
        {
            var userId = Convert.ToInt64(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var user = await _userRepository.Get(userId);

            var itemCount = await _orderRepository.GetOrderItemCount(user);
            return Json(new { success = true, itemCount });
        }

        [HttpGet]
        public async Task<IActionResult> Cart(Int64 Id = 0)
        {
            var order = new Order();

            if(Id == 0)
            {
                var userId = Convert.ToInt64(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var user = await _userRepository.Get(userId);

                order = await _orderRepository.GetOrderByUser(user);
            }
            else
            {
                order = await _orderRepository.Get(Id);
            }

            return View(order);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveItem(Int64 dishId, Int64 orderId)
        {
            try
            {
                await _orderRepository.RemoveItem(dishId, orderId);

                TempData["Success"] = "The operation occurred successfully";
            }
            catch (Exception)
            {
                TempData["Error"] = "The operation has failed";

            }

            return RedirectToAction(nameof(Cart));

        }

        [HttpGet]
        public async Task<IActionResult> Finish(Int64 Id)
        {
            try
            {
                var order = await _orderRepository.Get(Id);
                order.OrderStatus = Core.Enums.OrderStatus.Processing;

                await _orderRepository.Update(order);

                TempData["Success"] = "You've finished the order proccess, wait for the Chef!";
            }
            catch (Exception)
            {
                TempData["Error"] = "The operation has failed";

            }

            return RedirectToAction(nameof(Thanks));
        }

        [HttpGet]
        public async Task<IActionResult> Cancel(Int64 Id)
        {
            try
            {
                var order = await _orderRepository.Get(Id);
                order.OrderStatus = Core.Enums.OrderStatus.Cancelled;

                await _orderRepository.Update(order);

                TempData["Success"] = "You've canceled the order proccess, make a new Order!";
            }
            catch (Exception)
            {
                TempData["Error"] = "The operation has failed";
            }

            return RedirectToAction("Index", "Dishes");

        }

        [HttpGet]
        public async Task<IActionResult> Thanks()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> History()
        {
            var userId = Convert.ToInt64(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var user = await _userRepository.Get(userId);

            var orders = await _orderRepository.GetListOrderByUser(user);

            return View(orders);
        }
    }
}

NetRestaurant.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetRestaurant.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetRestaurant.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">

</head>
<body>
    <div class="d-flex">
        <nav class="bg-primary text-white vh-100 nav-primary">
            <div class="d-flex justify-content-center py-3">
                <div class="bg-white rounded-circle" style="width: 80px; height: 80px">
                    <img src="~/images/logo-net-restaurant.png" class="img-fluid" />
                </div>
            </div>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Home" asp-area="Admin" class="nav-link">
                        Admin
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Dishes" class="nav-link">
                        Dishes
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-action="History" asp-controller="Order" class="nav-link">
                        History
                    </a>
                </li>

            </ul>
        </nav>

        <div class="flex-grow-1  position-relative main-container">
            <nav class="navbar navbar-expand-lg bg-primary">
                <div class="container-fluid">
                    <span class="navbar-brand text-white">@ViewBag.Title</span>
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <div class="ml-auto d-flex gap-4">
                            <div class="shopping-cart position-relative">
                                <a asp-action="Cart" asp-controller="Order" class="btn btn-light text-primary">
                                    <i class="fa fa-shopping-cart"></i>
                                    <span id="cart-count">
                                        0
                                    </span>
                                </a>
                            </div>

                            <a asp-action="Logout" asp-controller="Login" class="btn text-white">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                Logout
                            </a>
                        </div>
                    }
                </div>
            </nav>
            <main role="main" class="p-4">
                @RenderBody()
            </main>
            <footer class="bg-primary p-3 position-fixed bottom-0 w-100 text-white d-flex justify-content-center" style="left: 0">
                &copy; 2024 - NetRestaurant - ASP.NET Core MVC Simplified: Master What You Need
            </footer>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/orderCount.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <partial name="_Toastr" />

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetRestaurant.UI/Views/Shared/_LoginForm.cshtml
@model LoginVM

<form asp-action="Index" asp-controller="Login" method="post" id="LoginForm">
    <div>
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Password" class="form-label"></label>
        <input asp-for="Password" type="password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="text-center mt-3">
        <p>
            Don't have an account?
            <a href="#" id="switchToRegister">Register Here</a>
        </p>
    </div>
    <div class="d-grid mt-4">
        <button class="btn btn-primary btn-lg">Login</button>
    </div>
</form>

<script>
    
</script>

NetRestaurant.UI/Views/Shared/_RegisterForm.cshtml
@model UserVM

<form asp-action="Register" asp-controller="Login" method="post" asp-route-id="@Model.Id">
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Password" class="form-label">Password</label>
        <input asp-for="Password" type="password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Address" class="form-label">Address</label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>

    <div class="text-center mt-3">
        <p>
            Already have an account?
            <a href="#" id="switchToLogin">Login Here</a>
        </p>
    </div>

    <div class="d-grid">
        <button class="btn btn-primary btn-lg">Register</button>
    </div>
</form>

NetRestaurant.UI/Views/Shared/_Toastr.cshtml
<script>
    toastr.options = {
        closeButton: true,
        progressBar: true,
        timeOut: 5000,
        positionClass: "toast-bottom-right"
    }

    @if (TempData["Success"] != null)
    {
        <text>
                    console.log('@TempData["Success"]')
                    toastr.success('@TempData["Success"]')
        </text>
    }

    @if (TempData["Error"] != null)
    {
        <text>
                    console.log('@TempData["Error"]')
                    toastr.error('@TempData["Error"]')
        </text>
    }
</script>