NetRestaurant.UI/Areas/Admin/Controllers/CategoriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetRestaurant.Core.Entities;
using NetRestaurant.Infrastructure.Repositories;
using NetRestaurant.UI.Areas.Admin.ViewModels;

namespace NetRestaurant.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("/admin/[controller]/[action]")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class CategoriesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly CategoryRepository _categoryRepository;

        public CategoriesController(IMapper mapper, CategoryRepository categoryRepository)
        {
            _mapper = mapper;
            _categoryRepository = categoryRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryRepository.GetAll());
        }

        public async Task<IActionResult> Edit(Int64 id = 0)
        {
            var category = await _categoryRepository.Get(id);
            var categoryVM = new CategoryVM();

            if (category == null)
                return View(categoryVM);

            categoryVM = _mapper.Map<Category, CategoryVM>(category);

            return View(categoryVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryVM categoryVM)
        {
            var category = _mapper.Map<CategoryVM, Category>(categoryVM);

            try
            {
                if (category.Id == 0)
                    await _categoryRepository.Create(category);
                else
                    await _categoryRepository.Update(category);

                TempData["Success"] = "The operation occurred successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "The operation has failed";
                return View(categoryVM);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Int64 id)
        {
            try
            {
                var isDeleted = await _categoryRepository.Delete(id);

                if (isDeleted)
                    TempData["Success"] = "The category was deleted successfully";
                else
                    TempData["Error"] = "An error ocorred with the operation";

            }
            catch (Exception ex)
            {
                TempData["Error"] = "The operation has failed";
            }

            return RedirectToAction(nameof(Index));

        }
    }
}

NetRestaurant.UI/Areas/Admin/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetRestaurant.Core.Enums;
using NetRestaurant.Infrastructure.Repositories;

namespace NetRestaurant.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("/admin/[controller]/[action]")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class OrdersController : Controller
    {
        private readonly IMapper _mapper;
        private readonly OrderRepository _orderRepository;

        public OrdersController(IMapper mapper, OrderRepository orderRepository)
        {
            _mapper = mapper;
            _orderRepository = orderRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _orderRepository.GetAll());
        }

        public async Task<IActionResult> Details(Int64 Id)
        {
            return View(await _orderRepository.Get(Id));
        }

        public async Task<IActionResult> SetStatus(Int64 Id, int status)
        {
            var order = await _orderRepository.Get(Id);
            order.OrderStatus = Enum.Parse<OrderStatus>(status.ToString());

            await _orderRepository.Update(order);

            return RedirectToAction(nameof(Details), new { Id = Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Int64 id)
        {
            try
            {
                var isDeleted = await _orderRepository.Delete(id);

                if (isDeleted)
                    TempData["Success"] = "The order was deleted successfully";
                else
                    TempData["Error"] = "An error ocorred with the operation";

            }
            catch (Exception ex)
            {
                TempData["Error"] = "The operation has failed";
            }

            return RedirectToAction(nameof(Index));

        }
    }
}

NetRestaurant.UI/Areas/Admin/Controllers/UsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetRestaurant.Core.Entities;
using NetRestaurant.Infrastructure.Repositories;
using NetRestaurant.UI.ViewModels;

namespace NetRestaurant.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("/admin/[controller]/[action]")]
    [Authorize(AuthenticationSchemes = "AdminCookie")]
    public class UsersController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly IMapper _mapper;

        public UsersController(UserRepository userRepository, IMapper mapper)
        {
            _userRepository = userRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _userRepository.GetAll());
        }

        public async Task<IActionResult> Edit(Int64 id = 0)
        {
            var user = await _userRepository.Get(id);
            var userVM = new UserVM();

            if (user == null)
                return View(userVM);

            userVM = _mapper.Map<User, UserVM>(user);

            return View(userVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserVM userVM)
        {
            var user = _mapper.Map<UserVM, User>(userVM);

            try
            {
                if (user.Id == 0)
                    await _userRepository.Create(user);
                else
                    await _userRepository.Update(user);

                TempData["Success"] = "The operation occurred successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "The operation has failed";
                return View(userVM);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Int64 id)
        {
            try
            {
                var isDeleted = await _userRepository.Delete(id);

                if (isDeleted)
                    TempData["Success"] = "The user was deleted successfully";
                else
                    TempData["Error"] = "An error ocorred with the operation";

            }
            catch (Exception ex)
            {
                TempData["Error"] = "The operation has failed";
            }

            return RedirectToAction(nameof(Index));

        }
    }
}

NetRestaurant.UI/Controllers/LoginController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using NetRestaurant.Core.Entities;
using NetRestaurant.Infrastructure.Repositories;
using NetRestaurant.UI.ViewModels;
using System.Security.Claims;

namespace NetRestaurant.UI.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserRepository _userRepository;
        private readonly IMapper _mapper;

        public LoginController(UserRepository userRepository, IMapper mapper)
        {
            _userRepository = userRepository;
            _mapper = mapper;
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginVM login)
        {
            try
            {
                var user = await _userRepository.GetByEmailPassword(login.Email, login.Password);

                if (user == null)
                {
                    return Json(new { success = false, message = "Invalid login credentials." } );
                }

                await Authenticate(user);

                return Json(new { success = true, redirectUrl = Url.Action("Index", "Dishes") });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "An unexpected error occurred. Please try again." });
            }
        }



        [HttpPost]
        public async Task<IActionResult> Register(UserVM userVM)
        {
            var user = _mapper.Map<UserVM, User>(userVM);

            try
            {
                if (user.Id == 0)
                    await _userRepository.Create(user);
                else
                    await _userRepository.Update(user);

                await Authenticate(user);

                TempData["Success"] = "The operation occurred successfully";
            }
            catch (Exception ex)
            {
                TempData["Error"] = "The operation has failed";
                return View(userVM);
            }

            return RedirectToAction("Index", "Dishes");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Dishes");
        }

        private async Task Authenticate(User user)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Name),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Role, "User")
            };

            var identiy = new ClaimsIdentity(claims, "UserCookie");
            var principal = new ClaimsPrincipal(identiy);

            await HttpContext.SignInAsync("UserCookie", principal);
        }
    }
}

NetRestaurant.UI/Areas/Admin/Views/Shared/_DataTable.cshtml
<link href="https://cdn.datatables.net/1.13.5/css/dataTables.bootstrap5.min.css" rel="stylesheet">


<script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap5.min.js"></script>

<script>
    $(document).ready(function() {
        $("#DataTable").DataTable({
            resposive: true,
            pageLength: 30,
            lengthMenu: [5, 10, 30, 100],
            order: [[0, 'asc']]
        })
    })
</script>

NetRestaurant.UI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetRestaurant.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetRestaurant.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">

</head>
<body>
    <div class="d-flex">
        <nav class="bg-primary text-white vh-100 nav-primary">
            <div class="d-flex justify-content-center py-3">
                <div class="bg-white rounded-circle" style="width: 80px; height: 80px">
                    <img src="~/images/logo-net-restaurant.png" class="img-fluid" />
                </div>
            </div>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link text-white" data-bs-toggle="collapse" href="#ordersMenu" role="button" aria-expanded="false" aria-controls="ordersMenu">
                        <i class="fa-solid fa-cart-shopping"></i> Orders
                    </a>
                    <div class="collapse" id="ordersMenu">
                        <ul class="nav flex-column ms-3">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Orders" class="nav-link">
                                    List
                                </a>
                                <a asp-action="Edit" asp-controller="Orders" asp-route-id="0" class="nav-link">
                                    Create
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" data-bs-toggle="collapse" href="#CategoriesMenu" role="button" aria-expanded="false" aria-controls="CategoriesMenu">
                        <i class="fa-solid fa-layer-group"></i> Categories
                    </a>
                    <div class="collapse" id="CategoriesMenu">
                        <ul class="nav flex-column ms-3">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Categories" class="nav-link">
                                    List
                                </a>
                                <a asp-action="Edit" asp-controller="Categories" asp-route-id="0" class="nav-link">
                                    Create
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" data-bs-toggle="collapse" href="#UsersMenu" role="button" aria-expanded="false" aria-controls="UsersMenu">
                        <i class="fa-solid fa-user"></i> Users
                    </a>
                    <div class="collapse" id="UsersMenu">
                        <ul class="nav flex-column ms-3">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Users" class="nav-link">
                                    List
                                </a>
                                <a asp-action="Edit" asp-controller="Users" asp-route-id="0" class="nav-link">
                                    Create
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" data-bs-toggle="collapse" href="#DishesMenu" role="button" aria-expanded="false" aria-controls="DishesMenu">
                        <i class="fa-solid fa-utensils"></i> Dishes
                    </a>
                    <div class="collapse" id="DishesMenu">
                        <ul class="nav flex-column ms-3">
                            <li class="nav-item">
                                <a asp-action="Index" asp-controller="Dishes" class="nav-link">
                                    List
                                </a>
                                <a asp-action="Edit" asp-controller="Dishes" asp-route-id="0" class="nav-link">
                                    Create
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </nav>

        <div class="flex-grow-1  position-relative main-container">
            <nav class="navbar navbar-expand-lg bg-primary">
                <div class="container-fluid">
                    <span class="navbar-brand text-white">@ViewBag.Title</span>
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <div class="ml-auto">
                            <a asp-action="Logout" asp-controller="Login" class="btn text-white">
                                <i class="fa fa-sign-out" aria-hidden="true"></i>
                                Logout
                            </a>
                        </div>
                    }
                </div>
            </nav>
            <main role="main" class="p-4">
                @RenderBody()
            </main>
            <footer class="bg-primary p-3 position-fixed bottom-0 w-100 text-white d-flex justify-content-center" style="left: 0">
                &copy; 2024 - NetRestaurant - ASP.NET Core MVC Simplified: Master What You Need
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <partial name="_Toastr" />


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>